### PR TITLE
(#3) atlantis: add crontab files

### LINKED ISSUE #3: add crontab and shell script for atlantis backup

### PR DESCRIPTION
**Pull request by sebhtml**

### CODE REVIEW

**Review by zorino — CHANGES_REQUESTED** [review]
Instead of setting env variables for the ssh agents especially from the tmp directory I would use a background ssh-agent process like this : `ssh-agent -s` and kill the ssh-agent process after running your python script with `kill $SSH_AGENT_PID` .
see https://stackoverflow.com/questions/2205282/ssh-agent-and-crontab-is-there-a-good-way-to-get-these-to-meet
Note that the ssh key probably have to be in the home directory and named id_rsa ~/.ssh/id_rsa

**Comment by sebhtml** [comment]
> Instead of setting env variables for the ssh agents especially from the tmp directory I would use a background ssh-agent process like this : `ssh-agent -s` and kill the ssh-agent process after running your python script with `kill $SSH_AGENT_PID` .
> see https://stackoverflow.com/questions/2205282/ssh-agent-and-crontab-is-there-a-good-way-to-get-these-to-meet
> Note that the ssh key probably have to be in the home directory and named id_rsa ~/.ssh/id_rsa

Hey Zorino ! long time no see

You're probably right on this.

Let me explain my context.

* My "ssh-agent" process is running inside tmux. So it is not a background process, but it remains alive as long as the tmux does.
* The content of ssh-agent.txt in my commit is the output of `ssh-agent -s`
* My SSH private key is protected by a password, so I don't know how to automate this.
* My SSH private key is not in ~/.ssh/id_rsa, it is stored in /root/atlantis-root-key.pem

I hope that makes sense.

**Comment by zorino** [comment]
Ok then if it works in your settings I see no need to keep blocking the merge.

**Comment by sebhtml** [comment]
I reopened it.
Can you accept the pull request and merge it with the buttons ?

**Review by zorino — APPROVED** [review]

**Comment by sebhtml** [comment]
@zorino Thank you for your time ! Much appreciated.

**Pull request merged**
